version: '3.8'
services:
  backend:
    image: codeerror404/java-crud
    pull_policy: always
    ports:
      - "8181:8181"
    depends_on:
        - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5438/postgres
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SERVER_PORT=8181
      - LOGBACK_DESTINATION_URL=${ELK_URL}

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5438:5438"
    command: -p 5438
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:

