name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  push_compose:
    name: Push docker-compose.yaml to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}"
          overwrite: true

  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Review Bot Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: codeerror404/java-crud

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [ build_and_push_images, push_compose ]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            
            echo DB_USER = ${{ secrets.DB_USER }} >> java-crud-env.txt
            echo DB_PASS = ${{ secrets.DB_PASS }} >> java-crud-env.txt
            
            sudo -S docker stop java-crud
            sudo -S docker rm java-crud
            sudo -S docker rmi codeerror404/java-crud
            sudo -S docker-compose -f docker-compose.yml --env-file=java-crud-env.txt up -d
            sudo -S docker ps -a  
            
            rm java-crud-env.txt